import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;
final class DecoratorPattern{
  static final class PatternException extends RuntimeException{private final String code;PatternException(String c){super(c);code=c;}String code(){return code;}}
  interface Client{Map<String,Object>send(Map<String,Object>request);}
  @SuppressWarnings("unchecked")static Map<String,Object>copy(Map<String,Object>request){Map<String,Object>v=new LinkedHashMap<>(request);v.put("headers",new LinkedHashMap<>((Map<String,Object>)request.getOrDefault("headers",Map.of())));v.put("applied",new ArrayList<>((List<String>)request.getOrDefault("applied",List.of())));return v;}
  static final class BaseClient implements Client{public Map<String,Object>send(Map<String,Object>request){Map<String,Object>v=copy(request),r=new LinkedHashMap<>();r.put("path",v.get("path"));r.put("headers",v.get("headers"));r.put("applied",v.get("applied"));return r;}}
  static final class AuthDecorator implements Client{private final Client next;private final String token;AuthDecorator(Client n,String t){next=n;token=t;}@SuppressWarnings("unchecked")public Map<String,Object>send(Map<String,Object>request){if(token==null||token.isEmpty())throw new PatternException("missing_token");Map<String,Object>v=copy(request);((Map<String,Object>)v.get("headers")).put("Authorization","Bearer "+token);((List<String>)v.get("applied")).add("auth");return next.send(v);}}
  static final class TraceDecorator implements Client{private final Client next;TraceDecorator(Client n){next=n;}@SuppressWarnings("unchecked")public Map<String,Object>send(Map<String,Object>request){String trace=String.valueOf(request.getOrDefault("trace_id",""));if(trace.isEmpty())throw new PatternException("missing_trace");Map<String,Object>v=copy(request);((Map<String,Object>)v.get("headers")).put("X-Trace-Id",trace);((List<String>)v.get("applied")).add("trace");return next.send(v);}}
  @SuppressWarnings("unchecked")static Object evaluate(Map<String,Object>input){Client client=new BaseClient();List<Object>decorators=(List<Object>)input.getOrDefault("decorators",List.of());for(int i=decorators.size()-1;i>=0;i--){String name=String.valueOf(decorators.get(i));client=switch(name){case"auth"->new AuthDecorator(client,(String)input.get("token"));case"trace"->new TraceDecorator(client);default->throw new PatternException("unsupported_decorator");};}List<Map<String,Object>>out=new ArrayList<>();for(Map<String,Object>request:(List<Map<String,Object>>)input.getOrDefault("requests",List.of()))out.add(client.send(request));return Map.of("responses",out);}}
